FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Demo Payments API

This is a simple REST API that allows the fetching, creation, updating and deletion of payments.

## Payment [/payment]

### Create a payment [POST]

### Update a payment [PUT]

### Remove a payment [DELETE]

### Get a payment by ID [GET]

### Get all payments [GET]