FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Payments

Payments is a simple REST API that allows the fetching, creation, updating and deletion of payments.

## Payment [/payment]

A single Payment object with all its details

### Get a payment [GET]

### Create a payment [POST]

### Update a payment [PUT]

### Remove a payment [POST]


## Payment Collection [/payments]

### Get a list of payments [GET]