/**
 * Model generated from JSON by RoboPOJOGenerator: https://github.com/robohorse/RoboPOJOGenerator
 */

package com.form3.payments.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Payment")
public class Payment {

  private String id;
  private String type;

  private String organisationId;
  private int version;
  private Attributes attributes;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  // note that tye isn't an @Attribute in the DB, since we only store objects that have type=Payment
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  @DynamoDBAttribute
  public int getVersion() {
    return version;
  }

  public void setVersion(int version) {
    this.version = version;
  }

  @DynamoDBAttribute
  public String getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(String organisationId) {
    this.organisationId = organisationId;
  }

  @DynamoDBAttribute
  public Attributes getAttributes() {
    return attributes;
  }

  public void setAttributes(Attributes attributes) {
    this.attributes = attributes;
  }


  @Override
  public String toString() {
    return
        "Payment{" +
            "organisation_id = '" + organisationId + '\'' +
            ",id = '" + id + '\'' +
            ",type = '" + type + '\'' +
            ",version = '" + version + '\'' +
            ",attributes = '" + attributes + '\'' +
            "}";
  }
}
