/**
 * Model generated from JSON by RoboPOJOGenerator: https://github.com/robohorse/RoboPOJOGenerator
 */

package com.form3.payments.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBGeneratedUuid;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Payment")
public class Payment {

  @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.CREATE)
  private String id;
  private String type;

  private String organisationId;
  private int version;
  private Attributes attributes;

  @DynamoDBHashKey(attributeName = "Id")
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  public Payment setId(String id) {
    this.id = id;
    return this;
  }

  public boolean hasId() {
    return id != null;
  }

  public String getType() {
    return type;
  }

  public Payment setType(String type) {
    this.type = type;
    return this;
  }

  public int getVersion() {
    return version;
  }

  public Payment setVersion(int version) {
    this.version = version;
    return this;
  }

  public String getOrganisationId() {
    return organisationId;
  }

  //
  public Payment setOrganisationId(String organisationId) {
    this.organisationId = organisationId;
    return this;
  }

  public Attributes getAttributes() {
    return attributes;
  }

  public Payment setAttributes(Attributes attributes) {
    this.attributes = attributes;
    return this;
  }

  @Override
  public String toString() {
    return
        "Payment{" +
            "organisation_id = '" + organisationId + '\'' +
            ",id = '" + id + '\'' +
            ",type = '" + type + '\'' +
            ",version = '" + version + '\'' +
            ",attributes = '" + attributes + '\'' +
            "}";
  }
}
