/**
 * Model generated from JSON by RoboPOJOGenerator: https://github.com/robohorse/RoboPOJOGenerator
 */

package com.form3.payments.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Payment")
public class Payment {

  private String id;
  private String type;

  private String organisationId;
  private int version;
  private Attributes attributes;



  // Constructor that takes id, used for testing
  public Payment(String id) {
    this.id = id;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  public Payment setId(String id) {
    this.id = id;
    return this;
  }

  // note that type isn't an @Attribute in the DB, since we only store objects that have type=Payment
  public String getType() {
    return type;
  }

  public Payment setType(String type) {
    this.type = type;
    return this;
  }

  @DynamoDBAttribute
  public int getVersion() {
    return version;
  }

  public Payment setVersion(int version) {
    this.version = version;
    return this;
  }

  @DynamoDBAttribute
  public String getOrganisationId() {
    return organisationId;
  }

  //
  public Payment setOrganisationId(String organisationId) {
    this.organisationId = organisationId;
    return this;
  }

  @DynamoDBAttribute
  public Attributes getAttributes() {
    return attributes;
  }

  public Payment setAttributes(Attributes attributes) {
    this.attributes = attributes;
    return this;
  }


  @Override
  public String toString() {
    return
        "Payment{" +
            "organisation_id = '" + organisationId + '\'' +
            ",id = '" + id + '\'' +
            ",type = '" + type + '\'' +
            ",version = '" + version + '\'' +
            ",attributes = '" + attributes + '\'' +
            "}";
  }
}
